made all endpoints

diff --git a/project/Dockerfile b/project/Dockerfile
--- a/project/Dockerfile
+++ b/project/Dockerfile
@@ -1,67 +1,37 @@
-FROM php:8.1-cli-buster
-
-# Arguments defined in docker-compose.yml
-ARG user='nonroot'
-ARG uid=1000
-
-# Установить системные зависимости
-RUN apt-get update \
-    && apt-get install -y \
-        libpq-dev \
-        libssl-dev \
-        libcurl4-openssl-dev \
-        curl \
-        zip \
-        unzip \
-        procps \
-        openssl \
-        wget \
-        git \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/*
-
-# Установить расширения PHP
-RUN docker-php-ext-install \
-    sockets \
-    pcntl
-
-# Install Swoole
-RUN cd /tmp && git clone https://github.com/swoole/swoole-src.git \
-    && cd swoole-src \
-    && git checkout v4.8.11 \
-    && phpize \
-    && ./configure --enable-openssl --enable-swoole-curl --enable-http2 --enable-mysqlnd \
-    && make && make install \
-    && touch /usr/local/etc/php/conf.d/swoole.ini \
-    && echo 'extension=swoole.so' > /usr/local/etc/php/conf.d/swoole.ini \
-    && wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
-    && chmod +x /usr/local/bin/dumb-init \
-    && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
-
-# Получить последнюю версию Composer
-COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
-
-# Добавьте wait к изображению
+FROM alpine/git:v2.32.0 as wait
 ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.8.0/wait /wait
+
+
+FROM php:8.1.6-alpine
+
+ARG DEBUG='false'
+ARG RUN_DEPS='postgresql-libs'
+ARG BUILD_DEPS='postgresql-dev'
+ARG PHP_EXTENSIONS='sockets pcntl pdo_pgsql'
+
+# Validate args
+RUN if [ $DEBUG != 'true' && $DEBUG != 'false' ]; then echo 'DEBUG argument must be `true` or `false`!'; exit 1; fi
+
+# Preparing system
+RUN echo 'UTC' > /etc/timezone
+COPY --from=wait /wait /.
 RUN chmod +x /wait
-
-# Create system user to run Composer and Artisan Commands
-RUN useradd -G www-data,root -u $uid -d /home/$user $user
-RUN mkdir -p /home/$user/.composer && \
-    chown -R $user:$user /home/$user
-
-RUN mkdir /app \
-    && chmod -R 755 /app \
-    && chown -R $user:$user /app
-
-USER $user
-
+RUN apk add --no-cache --virtual .build-deps $BUILD_DEPS \
+    && docker-php-ext-install -j "$(nproc)" $PHP_EXTENSIONS \
+    && apk del .build-deps
+RUN apk add --no-cache --virtual .run-deps $RUN_DEPS
+COPY --from=composer /usr/bin/composer /usr/bin/composer
 WORKDIR /app
 
-COPY --chown=$user composer.json .
-COPY --chown=$user composer.lock .
-RUN composer install --no-interaction --no-progress --no-autoloader --dev
-COPY --chown=$user . .
+# Preparing code base
+COPY composer.json .
+COPY composer.lock .
+RUN composer install --no-interaction --no-progress --no-autoloader --no-cache \
+    $(if [ $DEBUG == 'true' ]; then echo '--dev'; else echo '--no-dev'; fi)
+COPY . .
 RUN composer dump-autoload
-RUN chmod 777 /app
-CMD /wait && ./server
+
+# Cleanup before run
+RUN if [ $DEBUG == 'false' ]; then rm /usr/bin/composer; fi
+
+CMD /wait && php artisan migrate --force && php artisan egal:run
